language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Golovanova_All_Lab
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
notifications:
  email: false
